baseurl = "/"
Paginate = 5

[params]
  env = "production"

[[menu.main]]
  name = "Головна"
  weight = 1
  identifier = "home"
  url = "/"
  
 [[menu.main]]
 name = "Контакти"
  weight = 120
  identifier = "contact_page"
  url = "/contact_page"

# datocms:start
title = "Creative Inc."
languageCode = "en"
# datocms:end
